# Generated by Django 2.0.6 on 2018-08-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='img',
            new_name='file_image',
        ),
    ]
