# Generated by Django 2.0.6 on 2018-08-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20180817_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
