# Generated by Django 2.0.6 on 2018-06-30 00:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 0, 5, 26, 353821, tzinfo=utc)),
        ),
    ]
