# Generated by Django 2.0.6 on 2018-06-30 00:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180630_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 0, 6, 2, 357358, tzinfo=utc)),
        ),
    ]
