# Generated by Django 2.0.6 on 2018-06-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180630_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
